# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78102af1fb3e3739c9c55a21e030389d454ab19e7199a23e8a7e4d532766b293178d5abcb7ebd742122699280fd62d3bdf05d27b81710549e7f670ae925b3b62

test:
  secret_key_base: b59909c92ba7febab0f8b3f487e755f990a9d0ad57aba8428654cf620f823a514ed370771860dcc0bbe920590d1187ead617021b80ca4d7a4d153d6af357a092

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
